# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stash_names', models.TextField(default='["bank account", "savings", "wallet", "others"]')),
                ('current_costs', models.TextField(default='["rent and other charges", "transportation", "clothes", "food", "hobby", "others"]')),
                ('monthly_costs', models.TextField(default='{"existence amount": 1500, "standard amount": 3000, "minimal amount": 2000}')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
