# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yourFinance', '0002_stash'),
    ]

    operations = [
        migrations.AddField(
            model_name='stash',
            name='name',
            field=models.CharField(choices=[('bank account', 'bank account'), ('savings', 'savings'), ('wallet', 'wallet'), ('others', 'others')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='stash_names',
            field=models.TextField(default='[["bank account", "bank account"], ["savings", "savings"], ["wallet", "wallet"], ["others", "others"]]'),
        ),
    ]
