# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourFinance', '0005_stash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stash',
            name='name',
            field=models.CharField(choices=[('Bank account', 'bank acc'), ('Savings', 'savings'), ('Wallet', 'wallet'), ('Others', 'others')], max_length=20),
        ),
    ]
