# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourFinance', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stash',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
