# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourFinance', '0008_auto_20170412_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stashNames',
            field=models.TextField(default='Bank account\nSavings\nWallet\nOthers\n'),
        ),
    ]
