# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourFinance', '0009_profile_stashnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='existenceLevel',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=8, verbose_name='Existence level monthly cost'),
        ),
        migrations.AddField(
            model_name='profile',
            name='minimalLevel',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=8, verbose_name='Minimal level monthly cost'),
        ),
        migrations.AddField(
            model_name='profile',
            name='standardLevel',
            field=models.DecimalField(decimal_places=2, default=3000.0, max_digits=8, verbose_name='Standard level monthly cost'),
        ),
    ]
