# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourFinance', '0012_auto_20170417_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stash',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
