# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourFinance', '0013_auto_20170420_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='existenceLevel',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='minimalLevel',
        ),
        migrations.AddField(
            model_name='profile',
            name='basicLevel',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=8, verbose_name='Basic level monthly cost'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mediumLevel',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=8, verbose_name='Medium level monthly cost'),
        ),
    ]
